export enum Template {
    CHARACTER = 'character',
    START = 'start',
    NEW_GAME_NEW = 'new-game-new',
    NEW_GAME_RESUMED = 'new-game-resumed',
    STATS = 'stats',
    ATTACK = 'attack',
    COMBAT_TURN = 'combat-turn',
    COMBAT_WIN = 'combat-win',
    COMBAT_LOSE = 'combat-lose',
    ENTER_ROOM = 'enter-room',
    GAME_WON = 'game-won',
    PATH_CHOICES = 'path-choices',
    CAMPFIRE = 'campfire',
    ALTAR = 'altar',
    ALTAR_DONE = 'altar-done',
    BLOOD_ALTAR = 'blood-altar',
    BLOOD_ALTAR_DONE = 'blood-altar-done',
    BLOOD_ALTAR_DEATH = 'blood-altar-death',
}
